### ISSUE TITLE
Duplicate entries in menu for devices that are removed and re-added

### ISSUE THREAD

**Issue by robled** [kgshank/gse-sound-output-device-chooser#10]
I often remove USB audio devices and JACK sources/sinks.  Each time this happens, it appears that a duplicate entry is created in the menu:

![screenshot](https://i.imgur.com/Oo44nFC.png)

In this case I have a single G930 device and a single JACK source/sink.

**Comment by kgshank** [comment]
Please post the console messages. This seems to be similar to https://github.com/kgshank/gse-sound-output-device-chooser/issues/8

**Comment by kgshank** [comment]
There is a new update in extensions.gnome.org. Can you confirm whether the issue is resolved?

**Comment by FrnchFrgg** [comment]
This doesn't seem fixed here, using latest version on extensions.gnome.org (since I have Gnome 3.22, I think I cannot use versions < 16 anyway). Those are "null sinks" created by pulseaudio-dlna (https://github.com/masmu/pulseaudio-dlna) when a device appears, and deleted when it goes offline. When deleted, the sink doesn't disappear from the device chooser menu.
