### ISSUE TITLE
GNOME 3.38 Support?

### ISSUE THREAD

**Issue by Scotty-Trees** [kgshank/gse-sound-output-device-chooser#116]
Gnome 3.38 has been released and was hoping to see your awesome extension get updated to support the latest release, thank you!

**Comment by ckotte** [comment]
You could add ```3.38``` to ```shell-version``` in metadata.json, install, and create a PR if the extension works on 3.38.

**Comment by devbranch-vadym** [comment]
I had the extension installed on 3.36; it stopped working since updating to 3.38.
I can confirm it still works on 3.38 after disabling Gnome's extensions versions validation:

```sh
gsettings set org.gnome.shell disable-extension-version-validation "true"
```

Thus, I've created a PR to include `3.38` to `metadata.json`.

https://github.com/kgshank/gse-sound-output-device-chooser/pull/118
