### ISSUE TITLE
Device did not have an appropriate card

### ISSUE THREAD

**Issue by wargreen** [kgshank/gse-sound-output-device-chooser#19]
Hi,
When used with the pulseaudio's jack sink, i got many "fake" jack sink in the menu, which can crash gnome if selected, and my syslog is flooded by :
org.gnome.Shell.desktop[4462]: (gnome-shell:4462): Gvc-WARNING **: Device did not have an appropriate card

Thanks for this extension !

**Comment by FrnchFrgg** [comment]
I think this is again an instance of issue #8 and #10 that I trigger here with dummy (null) sinks created by pulseaudio-dlna (see #10). None of these appear in the "ports" list of the preferences window.

**Comment by kgshank** [comment]
@FrnchFrgg the preferences dialog gets the list of ports from the `pactl list cards` command. From what you have stated, the PA you are using is a modified for some other purposes. Unfortunately, I don't have the time now to experiment with my system. Share me the console out from the above command and i will try to implement the changes. As for the sinks not removed from the list of available devices, send me out from the command `journalctl -b | grep -i "JS LOG:"` while adding the sink and removing the sink

**Comment by FrnchFrgg** [comment]
Le 08/11/2016 à 15:15, Gopi Sankar Karmegam a écrit :
> @FrnchFrgg <https://github.com/FrnchFrgg> the preferences dialog gets
> the list of ports from the |pactl list cards| command.

It seems the preferences dialog doesn't even list my hardware sound card 
here, nor my audio through HDMI (tough both are listed by |pacmd 
list-cards| and both appear in the applet submenu). I just checked 
again, and the "Port list" TreeView is completely empty. (Note that I 
can help finding the problem if you care, but I don't use that feature 
at all).

> From what you have stated, the PA you are using is a modified for some other purposes.

Not at all. It's a completely standard pulseaudio (from Debian). But I 
have a daemon that creates null sinks for each uPNP media renderer 
advertised on the network, and listens to the null sink monitor to 
forward the audio to the uPNP device. Since those devices come and go 
(my HIFI amplifier advertises its uPNP capabilities only when powered 
up), that triggers the bug.

Note that the bug *doesn't* trigger if I power up my amplifier, then 
power it down 20s afterwards. I then get the following journalctl output:

nov. 08 15:29:04 winterfell gnome-shell[23487]: JS LOG: Freebox Player 
(DLNA)
nov. 08 15:29:04 winterfell gnome-shell[23487]: JS LOG: Added: 
10:Freebox Player (DLNA):null
nov. 08 15:29:23 winterfell gnome-shell[23487]: JS LOG: Removed: 10

Adding/removing a null sink manually with pacmd doesn't trigger the bug 
either. On the other hand, I noticed that the extension doesn't react at 
all (no journalctl output) if I add/remove a null sink while the session 
is in "screensaver" mode (I just blank the screen here without 
auto-lock, but gnome-shell still shows its confidentiality curtain on 
mouse move, that I have to drag up). Maybe gnome-shell suspends the 
extension when the session is idle ?

I can't test now because my wife is using that computer, but I'll check 
soon.

I very much suspect that my bug can be exactly reproduced *without* 
pulseaudio-dlna (the daemon) and simply with a null sink added through 
an ssh connexion (which I did to test because I didn't want to move from 
my computer). The ssh connexion would be only to be able to modify the 
pulseaudio sinks without leaving the idle mode of gnome-shell.

**Comment by FrnchFrgg** [comment]
I just tested, and indeed, if the amplifier is powered up (or a null sink added manually) while the session is active (the extension reacts), then powered down (or removed manually) while the session is idle, then it never gets removed. Furthermore, when the session comes back, we get a strange thing:

nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Max Id:12
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: HDMI / DisplayPort 2
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Added: 1:HDMI / DisplayPort 2:hdmi-output-1
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Removed: 1
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: HDMI / DisplayPort
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Added: 2:HDMI / DisplayPort:hdmi-output-0
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Activated: 2
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Digital Output (S/PDIF)
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Added: 3:Digital Output (S/PDIF):iec958-stereo-output
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Line Out
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Added: 4:Line Out:analog-output-lineout
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Removed: 4
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Sortie vide
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Added: 9:Sortie vide:null
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Freebox Player (DLNA)
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Added: 10:Freebox Player (DLNA):null
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Sortie vide
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Added: 11:Sortie vide:null
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Max Id:13
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Microphone
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Added: 5:Microphone:analog-input-mic
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Removed: 5
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Microphone
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Added: 6:Microphone:analog-input-mic
nov. 08 15:54:44 winterfell gnome-shell[23487]: JS LOG: Activated: 6

It seems that the null sink entry is added twice (that shows in the menu) even if there is none at all remaining really...

**Comment by kgshank** [comment]
Are you using a different display language? Using a different language breaks the parser for the preferences dialog. 

For the main issue, shell does not activate the extensions in screensaver mode and when it comes back, the extensions are initialized, the bug you are experiencing is from the extension initialization code. The sink is  added and removed when the extension was not active. When it gets enabled, it just traverses through available id's and adds it to the list. This is a hack, I had to use as there is no direct way to get the list of ports available. It seems the port is not marked as inactive in gvc, that's why its not removed. I will see the feasibility to avoid this scenario

**Comment by FrnchFrgg** [comment]
Le 09/11/2016 à 17:51, Gopi Sankar Karmegam a écrit :
> Are you using a different display language? Using a different language
> breaks the parser for the preferences dialog.

Mmm. I didn't know that you had to rely on parsing localized output.

> For the main issue, shell does not activate the extensions in
> screensaver mode and when it comes back, the extensions are initialized,
> the bug you are experiencing is from the extension initialization code.
> The sink is added and removed when the extension was not active. When it
> gets enabled, it just traverses through available id's and adds it to
> the list.

Yes, I figured as much.

> This is a hack, I had to use as there is no direct way to get
> the list of ports available. It seems the port is not marked as inactive
> in gvc, that's why its not removed.

That might not be the only problem, because the port is not removed, but 
in fact another is wrongly created ! Maybe this is a bug in gvc. I 
suppose you cannot directly use a pulseaudio binding for enumeration 
(and maybe even signals), instead of relying on Gnome ?

_FrnchFrgg_
