### ISSUE TITLE
"Extension initialising..." is always shown in menu

### ISSUE THREAD

**Issue by kitingChris** [kgshank/gse-sound-output-device-chooser#42]
![screenshot from 2018-09-03 17-59-46](https://user-images.githubusercontent.com/757762/44995442-537c8680-afa3-11e8-9b12-890f434253b7.png)

$ gnome-shell --version
GNOME Shell 3.28.3

**Comment by NodokaMurmevent** [comment]
same problem with GNOME Shell 3.30.1

**Comment by bavramor** [comment]
Same Problem for me with Gnome-Shell 3.28.3.
Would there will be a fix for?

Thx

**Comment by npnufn** [comment]
unselect "Input Device"

**Comment by npnufn** [comment]
> Same Problem for me with Gnome-Shell 3.28.3.
> Would there will be a fix for?
> 
> Thx



> same problem with GNOME Shell 3.30.1
unselect "Input Device"

**Comment by joenoone** [comment]
Thought I had the same problem. I unselected "Input Device" and it still said the same. Then I chose my device in the list and it changed to that device name instead of "Extension Initializing".

**Comment by Natetronn** [comment]
Thanks for the extension. Unselecting "Input Device" worked for me.

**Comment by Sioma112233** [comment]
#57

**Comment by memeplex** [comment]
I'm having the same problem, extension built from repo, Arch Linux, Gnome 3.32. I tried disabling input devices, auto-hiding, etc. To no avail. I don't see how https://github.com/kgshank/gse-sound-output-device-chooser/pull/57 is related to this but, anyway, since I'm using the master branch I assume that hot fix is already here and has no effect.

**Comment by memeplex** [comment]
After one hundred reboots I think I've isolated the reason for this behavior, at least in my own setup, which I must admit is pretty non-standard: I use an external USB card plus pulseaudio equalizer (the LADSPA one, not the obsolete one), and keep a script subscribed to card creation/removal events so as to reconnect the equalizer to the new sink, set an a2dp profile for the bluetooth sink, etc. Moreover, `module-switch-on-connect` is enabled in my pulseaudio user configuration. Now, after removing all these pieces, one by one, the equalizer seems to be causing the problem, specifically removing the following from my default.pa:

```
### BEGIN: Equalized audio configuration
### Generated from: pulseaudio-equalizer
.nofail
load-module module-ladspa-sink sink_name=ladspa_output.mbeq_1197.mbeq sink_master=alsa_output.pci-0000_00_1b.0.analog-stereo plugin=mbeq_1197 label=mbeq control=4.8,4.8,3.5,2.5,0.0,-7.0,-14.0,-10.0,-10.0,-8.0,1.0,1.0,5.2,7.7,9.5
set-default-sink ladspa_output.mbeq_1197.mbeq
set-sink-mute alsa_output.pci-0000_00_1b.0.analog-stereo 0
.fail
### END: Equalized audio configuration
```

makes the "Extension initialising..." legend disappear.

Are other people here reporting similar problems using the equalizer like me?

**Comment by memeplex** [comment]
The sink is indeed added at shell startup:

```
ay 16 15:56:10 carlos gnome-shell[6501]: Added: 2:Headphones:analog-output-headphones
May 16 15:56:10 carlos gnome-shell[6501]: Added: 3:Speakers:analog-output-speaker
May 16 15:56:10 carlos gnome-shell[6501]: Added: 6:Digital Output (S/PDIF):iec958-stereo-output
May 16 15:56:10 carlos gnome-shell[6501]: Added: 7:Speakers:analog-output-speaker
May 16 15:56:10 carlos gnome-shell[6501]: Added: 9:LADSPA Plugin Multiband EQ on USB Audio Device Analog Stereo:null
```

Yet the "Exentension initialising..." item is there when the sink is the EQ. If afterwards I change the sink (using gnome sounds settings or even pactl) and set it to the EQ again, it's then correctly displayed by the extension.

**Comment by memeplex** [comment]
Ok, I managed to track down the problem and fix it. The stream for the equalizer has a null port, but during initialization streams with null ports aren't considered as possible default streams, so the legend is never updated. I'm not sure why the equal port check is relevant there, but I introduced a conservative change: accept a stream when both ports (stream and uidevice) are null or, otherwise, both ports are non-null and has the same number.

@kgshank could you take a look at https://github.com/kgshank/gse-sound-output-device-chooser/pull/61?
